[package]
name = "nash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall = "0.13.0"
unicode-segmentation = "1.11.0"
