FROM rust:1.74 as builder

WORKDIR /usr/src/nash

COPY ./src ./src
COPY Cargo.lock Cargo.toml ./
RUN cargo install --path .

FROM debian:bookworm
RUN apt-get --yes update && apt-get --yes install curl
COPY --from=builder /usr/local/cargo/bin/nash /bin/nash
