FROM rust:1.67 as builder

WORKDIR /usr/src/nash

COPY ./src ./src
COPY Cargo.lock Cargo.toml ./
RUN cargo install --path .

FROM debian:bookworm
COPY --from=builder /usr/local/cargo/bin/nash /bin/nash
