pub const KEYWORDS: [&str; 7] = ["if", "else", "func", "var", "exec", "true", "false"];
pub const IF: &str = KEYWORDS[0];
pub const ELSE: &str = KEYWORDS[1];
pub const FUNC: &str = KEYWORDS[2];
pub const VAR: &str = KEYWORDS[3];
pub const EXEC: &str = KEYWORDS[4];
pub const TRUE: &str = KEYWORDS[5];
pub const FALSE: &str = KEYWORDS[6];
pub const UNDERSCORE: &str = "_";
